[package]
name = "polonius-parser"
version = "0.1.0"
description = "Parser for the Polonius project"
license = "Apache-2.0/MIT"
authors = ["The Rust Project Developers", "Polonius Developers"]
repository = "https://github.com/rust-lang-nursery/polonius"
build = "build.rs" # LALRPOP preprocessing

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
lalrpop-util = "0.15.2"
regex = "1.0.0"
